spring:
  application:
    name: backend

  # db configs
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/codemind}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    open-in-view: false

  #  flyway:
  #    enabled: true
  #    locations: classpath:db/migration
  #    baseline-on-migrate: true

  ai:
    openai:
      api-key: ${OPEN_API_KEY}
      chat:
        model: gpt-4o-mini
      embedding:
        model: text-embedding-3-small

    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 1536
        index-type: HNSW
        distance-type: COSINE_DISTANCE

  #    ai:
  #      google:
  #        genai:
  #          api-key: ${GEMINI_API_KEY}
  #          chat:
  #            options:
  #              model: gemini-2.5-flash
  #          embedding:
  #            text:
  #              options:
  #                model: gemini-embedding-001
  #
  #      vectorstore:
  #        pgvector:
  #          initialize-schema: true
  #          dimensions: 3072
  #          index-type: NONE
  #          distance-type: COSINE_DISTANCE


  # GitHub oauth2 related configs
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user,repo
        provider:
          github:
            user-name-attribute: id

server:
  servlet:
    session:
      cookie:
        name: CODEMIND_SESSION
        http-only: true
        same-site: lax
      timeout: 7d


app:
  encrypt:
    password: ${ENCRYPTION_PASSWORD}
    salt: ${SALT_VALUE}
  frontend-url: ${FRONTEND_URL}
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
  indexing:
    max-file-bytes: 102400
    chunk-size: 800
    chunk-overlap: 100
  github:
    api-delay-ms: 50
